# @package _global_
auto_resume: True # Automatically resume if default experiment_folder and checkpoint exist
folder_override: "" # Override the folder name for the experiment - considered "resume" if folder has chpts
checkpoint_override: "" # Override the checkpoint file name for the experiment - considered "resume" if populated
config_override: "" # Override the config file name for the experiment
validation_mode: False