defaults:
  - trainer: defaults
  - optimizer: adam
  - experiment: ???
  - server: ???
  - resume_overrides: no_overrides
data:
  n_steps_input: 4
  n_steps_output: 1
  normalization_type: "zscore" # Norm type if use_normalization is set to be True in individual dataset;Options: zscore or rms or empty
  target_type: "full" # options: full or delta type prediction
# model:
#   gradient_checkpointing: False
data_workers: 14
wandb_project_name: "the_well_extended_again"
